enarocanje/service/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('enarocanje.service.views',
	url(r'^myservices/$', 'myservices', name='myservices'),
	url(r'^myunconfirmedreservations/managereservation$', 'managereservation', name='managereservation'),
	url(r'^myunconfirmedreservations/managereservationall$', 'managereservationall', name='managereservationall'),
	url(r'^myunconfirmedreservations/$', 'myunconfirmedreservations', name='myunconfirmedreservations'),
	url(r'^myservices/add$', 'add', name='addservice'),
	url(r'^myservices/manage$', 'manage', name='manageservice'),
	url(r'^myservices/edit/(?P<id>\d+)$', 'edit', name='editservice'),


	url(r'^$', 'browse_providers', name='browseproviders'),
	url(r'^services/$', 'browse_services', name='browseservices'),
	url(r'^services/(?P<id>\d+)/comments$', 'service_comments', name='servicecomments'),
    # 16.4.2014 RokA; added urls for browsing employees
    url(r'^employees/$', 'browse_employees', name='browseemployees'),

	url(r'^gallery/(?P<id>\d+)', 'view_gallery', name='gallery')
)

enarocanje/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^accounts/signup/$', 'enarocanje.accountext.views.singup'),
    url(r'^accounts/signup/provider/$', 'enarocanje.accountext.views.providersignup'),
	url(r'^accounts/profile/$', 'enarocanje.accountext.views.account_profile', name='account_profile'),

	url(r'^', include('enarocanje.service.urls')),
	url(r'^', include('enarocanje.workinghours.urls')),
	url(r'^', include('enarocanje.reservations.urls')),
	url(r'^', include('enarocanje.coupon.urls')),
    url(r'^', include('enarocanje.customers.urls')),
    url(r'^', include('enarocanje.ServiceProviderEmployee.urls')),
    url(r'^', include('enarocanje.mailservice.urls')),

	url(r'^web/(?P<serviceProviderWeb>\w+)/$', 'enarocanje.accountext.views.ServiceProviderWeb', name='provider_web'),

	# External apps
	url(r'^accounts/', include('allauth.urls')),

	# Django admin
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	url(r'^admin/', include(admin.site.urls)),

    # Cookies
    url(r'^cookies/$', TemplateView.as_view(template_name="cookies.html"),name='cookies'),
)

if settings.DEBUG:
	urlpatterns += patterns('',
		(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
	)

enarocanje/service/models.py
import datetime

from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.utils.translation import ugettext_lazy as _, ugettext

from enarocanje.accountext.models import ServiceProvider, User

class Category(models.Model):
	name = models.CharField(_('name'), max_length=100)

	def __unicode__(self):
		return "%s" % (self.name)

class Service(models.Model):
	MALE = 'm'
	FEMALE = 'f'
	SEX_SERVICE_CHOICES = (
		(MALE, _('Male')),
		(FEMALE, _('Female')),
	)

	service_provider = models.ForeignKey(ServiceProvider, related_name='services')
	name = models.CharField(_('name'), max_length=100)
	duration = models.PositiveIntegerField(_('duration'))
	description = models.TextField(_('description'), null=True, blank=True)
	price = models.DecimalField(_('price'), max_digits=7, decimal_places=2, null=True, blank=True)
	sex = models.CharField(_('sex'), choices=SEX_SERVICE_CHOICES, max_length=1, null=True, blank=True)
	category = models.ForeignKey(Category, null=True, blank=True)
	active_until = models.DateField(_('active until'), null=True, blank=True)

	def __unicode__(self):
		return unicode(self.name)

	def duration_with_unit(self):
		return u'%dmin' % self.duration

	def get_discount(self):
		try:
			return self.discounts.get(valid_from__lte=datetime.date.today(), valid_to__gte=datetime.date.today())
		except ObjectDoesNotExist:
			return None

	def discounted_price(self):
		discount = self.get_discount()
		if discount:
			return self.price - discount.discount * self.price / 100
		else:
			return self.price

	def price_with_unit(self):
		discount = self.get_discount()
		if discount:
			return u'%s\u20ac (%s -%d%%)' % (self.discounted_price(), ugettext(_('with')), discount.discount)
		else:
			return u'%s\u20ac' % self.price

	def is_active(self):
		return self.active_until is None or self.active_until >= datetime.date.today()

class Discount(models.Model):
	service = models.ForeignKey(Service, related_name='discounts', verbose_name=_('service'))
	discount = models.PositiveIntegerField(_('discount'))
	valid_from = models.DateField(_('discount valid from'))
	valid_to = models.DateField(_('discount valid to'))

	def discount_with_unit(self):
		return u'%d%%' % self.discount

class Comment(models.Model):
	service = models.ForeignKey(Service, related_name='comments', verbose_name=_('service'))
	author = models.ForeignKey(User, related_name='comments', verbose_name=_('author'))
	body = models.TextField(_('body'))
	created = models.DateTimeField(auto_now_add=True)

enarocanje/service/forms.py
from bootstrap_toolkit.widgets import BootstrapTextInput
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm, Textarea
from django.forms.models import inlineformset_factory, BaseInlineFormSet
from django.utils.translation import ugettext_lazy as _

from enarocanje.common.timeutils import is_overlapping
from enarocanje.common.widgets import BootstrapDateInput
from models import Service, Discount, Comment

class DiscountForm(ModelForm):
    valid_from = forms.DateField(widget=BootstrapDateInput(), label=_('Discount valid from'))
    valid_to = forms.DateField(widget=BootstrapDateInput(), label=_('Discount valid to'))

    def clean_valid_to(self):
        data = self.cleaned_data['valid_to']
        if not data:
            return data
        if not self.cleaned_data.get('valid_from'):
            return data
        if data and data <= self.cleaned_data['valid_from']:
            raise ValidationError(_('Discount can\'t end before it starts.'))
        return data

    class Meta:
        model = Discount
        # all fields except service
        exclude = ('service', )

class DiscountBaseFormSet(BaseInlineFormSet):

    def clean(self):
        intervals = []
        for form in self.forms:
            valid_from = form.cleaned_data.get('valid_from')
            valid_to = form.cleaned_data.get('valid_to')
            if valid_from and valid_to:
                for valid_from2, valid_to2 in intervals:
                    if is_overlapping(valid_from, valid_to, valid_from2, valid_to2):
                        raise ValidationError(_('Discounts can\'t overlap.'))
                intervals.append((valid_from, valid_to))

class ServiceForm(ModelForm):

    """Form for adding and editing services"""
    active_until = forms.DateField(widget=BootstrapDateInput(), required=False, label=_('Active until'))

    class Meta:
        model = Service
        # all fields except service_provider (you can only create your own services)
        exclude = ('service_provider',)

    def __init__(self, *args, **kwargs):
        super(ServiceForm, self).__init__(*args, **kwargs)
        self.fields['duration'].label = _('Duration (in minutes)')
        self.fields['price'].label = _('Price (in EUR)')

DiscountFormSet = inlineformset_factory(Service, Discount, form=DiscountForm, formset=DiscountBaseFormSet, extra=1)

class FilterForm(forms.Form):
    ACTIVE_CHOICES = (
        ('all', _('All')),
        ('active', _('Active')),
        ('inactive', _('Inactive'))
    )

    active = forms.ChoiceField(choices=ACTIVE_CHOICES, label='')

    def __init__(self, *args, **kwargs):
        durations = kwargs.pop('durations')
        discounts = kwargs.pop('discounts')
        super(FilterForm, self).__init__(*args, **kwargs)
        self.fields['duration'] = forms.ChoiceField(choices=[('all', _('All durations'))] + [(a, '%d min' % a) for a in durations], label='')
        self.fields['discount'] = forms.ChoiceField(choices=[('all', _('All discounts'))] + [(b, '%s' % b) for b in discounts], label='')

class CommentForm(ModelForm):

    class Meta:
        model = Comment
        fields = ('body',)

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['body'].label = ''

class EmailForm(forms.Form):
    subject = forms.CharField(widget=BootstrapTextInput(attrs={'style':'width:98%'}),label=_('Title'),required=True)
    message = forms.CharField(widget=Textarea(attrs={'style':'width:98%;max-width:98%'}),label=_('Text'),required=True)

templates/service/add.html
{% extends 'service/edit.html' %}

{% load i18n %}

{% block content_title %}{% trans "Add Service" %}{% endblock %}
{% block content_intro %}{% endblock %}

templates/service/comments.html
{% extends 'service/service.html' %}

{% load url from future %}
{% load i18n %}
{% load bootstrap_toolkit %}
{% load reservation %}

{% block service_nav_comments %}active{% endblock %}

{% block service_content %}

{% if form %}
	<h3>{% trans "Add your comment" %}</h3>
	<form action="" method="POST" class="comment-form">
		{% csrf_token %}
		{{ form|as_bootstrap }}
		<div class="form-actions">
			<button class="btn btn-primary" type="submit">{% trans "Submit" %}</button>
		</div>
	</form>
{% endif %}

{% for comment in comments %}
	<div class="comment well">
		<div class="metadata">
			{% trans "By" %} {{ comment.author.get_full_name }} {% trans "at" %} {{ comment.created }}
		</div>
		{{ comment.body }}
	</div>
{% empty %}
	{% if not form %}
		{% trans "No comments" %}
	{% endif %}
{% endfor %}

{% endblock %}

templates/service/edit.html
{% extends 'main.html' %}

{% load url from future %}
{% load i18n %}
{% load bootstrap_toolkit %}

{% block main_nav_myservices %}active{% endblock %}

{% block content %}

<h1>{% block content_title %}{% trans 'Edit Service' %}{% endblock %}</h1>

{% block content_intro %}
	<div style="margin-bottom: 20px">
		{% trans "Warning: previous reservations won't be affected by edits!" %}
	</div>
{% endblock %}

<form method="POST" action="">
		{% csrf_token %}
		<div class="row">
			<div class="span5">
				{% if form.non_field_errors %}
					{% include "bootstrap_toolkit/non_field_errors.html" %}
				{% endif %}
				{% for field in form.hidden_fields %}
					{{ field }}
				{% endfor %}
				{{ form.name|as_bootstrap }}
				{{ form.duration|as_bootstrap }}
				{{ form.price|as_bootstrap }}
				{{ form.category|as_bootstrap }}
				{{ form.sex|as_bootstrap }}
			</div>
			<div class="span7">
				{{ form.description|as_bootstrap }}
			</div>
		</div>
		<div class="toggle" style="margin-bottom: 14px">
			<div class="inactive">
				<a class="btn btn-info" href="#" style="display: none">{% trans "Set active until" %}</a>
			</div>
			<div class="active">
				{{ form.active_until|as_bootstrap }}
				<a class="btn btn-warning" href="#" style="margin-top: -10px; display: none">{% trans "Clear active until" %}</a>
			</div>
		</div>
	<h2>{% trans "Discounts" %}</h2>
	{{ formset.management_form }}
	{% if formset.non_form_errors %}
		<div class="alert alert-block alert-error">
			{% for error in formset.non_form_errors %}
				<p>{{ error }}</p>
			{% endfor %}
		</div>
	{% endif %}
	<div class="row">
		{% for subform in formset %}
			<div class="span4 twothree formset-form">
				<div class="formset-box well">
					{% if subform.non_field_errors %}
						{% with subform as form %}
							{% include "bootstrap_toolkit/non_field_errors.html" %}
						{% endwith %}
					{% endif %}
					{% for field in subform.hidden_fields %}
						{{ field }}
					{% endfor %}
					<div style="display: none">{{ subform.DELETE }}</div>
					{{ subform.discount|as_bootstrap }}
					{{ subform.valid_from|as_bootstrap }}
					{{ subform.valid_to|as_bootstrap }}
					<div class="delete-row"><i class="icon-remove"></i> {% trans "remove" %}</div>
					{% if forloop.last %}
						<div class="add-form-layer well">
							<i class="icon-plus"></i> {% trans "add a discount" %}
						</div>
					{% endif %}
				</div>
			</div>
		{% endfor %}
	</div>
		<div class="form-actions">
			<button class="btn btn-primary" type="submit" name="action">{% trans "Save" %}</button>
			<a class="btn" href="{% url 'myservices' %}">{% trans "Cancel" %}</a>
		</div>
</form>

{% endblock %}

{% block javascript %}
	{{ block.super }}
	(function(){
		function dateFields(el) {
			el.find('.date-field').parent().datetimepicker({pickTime: false, language: '{{ request.LANGUAGE_CODE }}'});
			$(document).trigger('sizing');
		}

		$('.formset-form').formset({
			'prefix': 'discounts',
			'added': dateFields
		});

		dateFields($('body'));
	})();
{% endblock %}

templates/service/myservices.html
{% extends 'main.html' %}

{% load url from future %}
{% load i18n %}
{% load bootstrap_toolkit %}

{% block main_nav_myservices %}active{% endblock %}

{% block content %}

<h1>{% trans 'My Services' %}</h1>

<ul class="nav nav-tabs">
	<li class="active">
		<a href="{% url 'myservices' %}">{% trans 'Services' %}</a>
	</li>
	<li>
		<a href="{% url 'mycoupons' %}">{% trans 'Coupons' %}</a>
	</li>
</ul>

<form method="GET" action="" id="filter-form">
	<b>{% trans 'Filter: ' %}</b>
	{{ filter_form.active }}
	{{ filter_form.duration }}
	{{ filter_form.discount }}
</form>

<div id="no-more-tables">
	<table class="table">
		<thead>
			<tr>
				<th>
					{% trans 'Name' %}
				</th>
				<th>
					{% trans 'Duration' %}
				</th>
				<th>
					{% trans 'Price' %}
				</th>
				<th>
					{% trans 'Category' %}
				</th>
				<th>
					{% trans 'Active until' %}
				</th>
				<th>
					{% trans 'Discount' %}
				</th>

				<th>
					{% trans 'Actions' %}
				</th>
			</tr>
		</thead>
		<tbody>
			{% for service in services %}
				<tr{% if not service.is_active %} class="warning"{% endif %}>
					<td data-title="{% trans 'Name' %}">
						{{ service.name }}
					</td>
					<td data-title="{% trans 'Duration' %}">
						{{ service.duration_with_unit }}
					</td>
					<td data-title="{% trans 'Price' %}">
						{% if service.price %}{{ service.price_with_unit }}{% else %}&nbsp;{% endif %}
					</td>
					<td data-title="{% trans 'Category' %}">
						{% if service.category %}{{ service.category }}{% else %}&nbsp;{% endif %}
					</td>
					<td data-title="{% trans 'Active until' %}">
						{% if service.active_until %}{{ service.active_until }}{% else %}&nbsp;{% endif %}
					</td>
					<td data-title="{% trans 'Discount' %}">
						{% for discount in service.discounts.all %}
						   {{ discount.discount_with_unit }} {{ discount.valid_from}} - {{ discount.valid_to }} <br/>{% if not forloop.last %} {% endif %}
						{% empty %}
						{% endfor %}

					</td>
					<td data-title="{% trans 'Actions' %}">
						<a class="btn" href="{% url 'editservice' service.id %}">{% trans "Edit" %}</a>
						<form method="POST" action="{% url 'manageservice' %}" style="display: inline">
							{% csrf_token %}
							<input type="hidden" name="service" value="{{ service.id }}" />
							{% if service.is_active %}
								<button class="btn btn-warning" type="submit" name="action" value="deactivate">{% trans "Deactivate" %}</button>
							{% else %}
								<button class="btn btn-success" type="submit" name="action" value="activate">{% trans "Activate" %}</button>
								<button class="btn btn-danger" type="submit" name="action" value="delete">{% trans "Delete" %}</button>
							{% endif %}
						</form>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

<div class="form-actions">
	<a class="btn btn-primary" href="{% url 'addservice' %}">{% trans "Add service" %}</a>
	<a class="btn btn-success" href="{% url 'gallery' user.service_provider_id %}">{% trans "View gallery" %}</a>
</div>

{% endblock %}

{% block javascript %}
	{{ block.super }}
	$('#id_active, #id_duration, #id_discount').change(function() {
		$('#filter-form').submit();
	});
{% endblock %}

templates/service/myunconfirmedreservation.html
{% extends 'main.html' %}

{% load url from future %}
{% load i18n %}
{% load bootstrap_toolkit %}

{% block main_nav_reservations %}active{% endblock %}

{% block content %}
<h1>{% trans 'My Reservations' %}</h1>
	<ul class="nav nav-tabs">
		<li>
			<a href="{% url 'myreservations_calendar' %}">{% trans 'Calendar' %}</a>
		</li>
        <li class="dropdown ">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            All Reservations
            <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
               <li> <a href="{% url 'myreservations_table' %}">{% trans 'All time' %}</a> </li>
               <li><a href="{% url 'myreservations_thisweek' %}">{%  trans 'This week' %}</a></li>
               <li><a href="{% url 'myreservations_nextweek' %}">{%  trans 'Next week' %}</a></li>
            </ul>
        </li>
		{% if res_confirm == True %}
			<li class="active">
			<a href="{% url 'myunconfirmedreservations' %}">{% trans 'Unconfirmed reservations' %}</a>
		</li>
		{% endif %}
    </ul>

	<div id="no-more-tables">
		<table class="table">
			<thead>
			<tr>
				<th>
					{% trans 'Name' %}
				</th>
				<th>
					{% trans 'Duration' %}
				</th>
				<th>
					{% trans 'Date and time' %}
				</th>
				<th>
					{% trans 'Actions' %}
				</th>

			</tr>
			</thead>
			<tbody>
			{% for uncon in unconfirmed %}
				<tr>
					<td data-title="{% trans 'Name' %}">
						 {{ uncon.service.name }}
					</td>
					<td data-title="{% trans 'Duration' %}">
						{{ uncon.service_duration }} min
					</td>
					<td data-title="{% trans 'Date and time' %}">
						{{ uncon.date }} {{ uncon.time }}
					</td>

					<td data-title="{% trans 'Actions' %}">
						<form method="POST" action="{% url 'managereservation' %}" style="display: inline">
							{% csrf_token %}
							<input type="hidden" name="reservation" value="{{ uncon.id }}" />
							<button class="btn btn-success" type="submit" name="action" value="confirm">{% trans "Confirm" %}</button>
							<button class="btn btn-danger" type="submit" name="action" value="deny">{% trans "Deny" %}</button>

						</form>
					</td>

				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>

	<div class="form-actions">

		<form method="POST" action="{% url 'managereservationall' %}" style="display: inline">
			{% csrf_token %}
			<button class="btn btn-success" type="submit" name="action" value="confirmall">{% trans "Confirm all" %}</button>
			<button class="btn btn-danger" type="submit" name="action" value="denyall">{% trans "Deny all" %}</button>
		</form>

	</div>
{% endblock %}

templates/service/service.html
{% extends 'main.html' %}

{% load url from future %}
{% load i18n %}
{% load bootstrap_toolkit %}

{% block extra_html_tag %}itemscope itemtype="http://schema.org/product"{% endblock %}

{% block extra_head_content  %}
	{{ block.super }}
	<meta itemprop="name" content="{{ service.name }}">
	<meta itemprop="description" content="{{ service.description }}">
	<meta itemprop="image" content="{{ service.service_provider.logo_absolute_url }}">
{% endblock %}

{% block content %}

	<div class="row">
		<div class="span12">
        {% if service_provider_employee_obj%}
			<h1><a style="color: #000000" href="{% url 'browseservices' %}?provider={{ service.service_provider.id }}">{{ service.service_provider.name }}</a> - <a style="color: #000000" href="{% url 'service' service.id service_provider_employee_obj.id %}">{{ service.name }}</a></h1>
        {% else %}
            <h1><a style="color: #000000" href="{% url 'browseservices' %}?provider={{ service.service_provider.id }}">{{ service.service_provider.name }}</a> - <a style="color: #000000" href="{% url 'service2' service.id %}">{{ service.name }}</a></h1>
        {% endif %}
			{% if service.description %}
				<p>{{ service.description }}</p>
			{% endif %}
			<p>
				<b>{% trans 'Duration' %}</b>: {{ service.duration_with_unit }}<br/>
			</p>
		    {% if service.price %}
		    	<p>
		    		<b>{% trans "Price" %}:</b> {{ service.price_with_unit }}<br/>
				    {% if service.is_discount_valid and service.discount_valid_to %}
				    	<b>{% trans "Discounted until" %}:</b> {{ service.discount_valid_to }}
					{% endif %}
				</p>
			{% endif %}
            {% if service_provider_employee_obj%}
		    	<p>
		    		<b>{% trans "Employee" %}:</b> {{ service_provider_employee_obj.first_name }} {{ service_provider_employee_obj.last_name }}<br/>
				</p>
            {% else %}

			{% endif %}
			<ul class="nav nav-tabs">
				<li class="{% block service_nav_reservation %}{% endblock %}">
                {% if service_provider_employee_obj%}
					<a href="{% url 'reservation' service.id service_provider_employee_obj.id %}">{% trans 'Reservation' %}</a>
                {% else %}
                    <a href="{% url 'reservation2' service.id %}">{% trans 'Reservation' %}</a>
                {% endif %}
				</li>
				<li class="{% block service_nav_comments %}{% endblock %}">
					<a href="{% url 'servicecomments' service.id %}">{% trans 'Comments' %}</a>
				</li>
			</ul>

			{% block service_content %}
			{% endblock %}

		</div>
	</div>
{% endblock %}