enarocanje/ServiceProviderEmployee/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('enarocanje.ServiceProviderEmployee',
	url(r'^myemployees/$', 'views.myemployees', name='myemployees'),
    url(r'^myemployees/add$', 'views.add', name='addemployee'),
	url(r'^myemployees/edit/(?P<id>\d+)$', 'views.edit', name='editemployee'),
    )

enarocanje/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^accounts/signup/$', 'enarocanje.accountext.views.singup'),
    url(r'^accounts/signup/provider/$', 'enarocanje.accountext.views.providersignup'),
	url(r'^accounts/profile/$', 'enarocanje.accountext.views.account_profile', name='account_profile'),

	url(r'^', include('enarocanje.service.urls')),
	url(r'^', include('enarocanje.workinghours.urls')),
	url(r'^', include('enarocanje.reservations.urls')),
	url(r'^', include('enarocanje.coupon.urls')),
    url(r'^', include('enarocanje.customers.urls')),
    url(r'^', include('enarocanje.ServiceProviderEmployee.urls')),
    url(r'^', include('enarocanje.mailservice.urls')),

	url(r'^web/(?P<serviceProviderWeb>\w+)/$', 'enarocanje.accountext.views.ServiceProviderWeb', name='provider_web'),

	# External apps
	url(r'^accounts/', include('allauth.urls')),

	# Django admin
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	url(r'^admin/', include(admin.site.urls)),

    # Cookies
    url(r'^cookies/$', TemplateView.as_view(template_name="cookies.html"),name='cookies'),
)

if settings.DEBUG:
	urlpatterns += patterns('',
		(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
	)

enarocanje/ServiceProviderEmployee/models.py
import datetime

from django.conf import settings
from django.db import models
from django.core.exceptions import ObjectDoesNotExist
from django.utils.translation import ugettext_lazy as _, ugettext

from enarocanje.accountext.models import ServiceProvider, User
from enarocanje.service.models import Service
# Create your models here.

# 2.4.2014 RokA; added class for Service Provider Employees
class ServiceProviderEmployee(models.Model):
    MALE = 'm'
    FEMALE = 'f'
    SEX_SERVICE_CHOICES = (
        (MALE, _('Male')),
        (FEMALE, _('Female')),
    )

    service_provider = models.ForeignKey(ServiceProvider, related_name='employees')
    service = models.ForeignKey(Service, related_name='employees', null=True, default=None)
    first_name = models.CharField(_('first_name'), max_length=100)
    last_name = models.CharField(_('last_name'), max_length=100)
    #sex = models.CharField(_('sex'), choices=SEX_SERVICE_CHOICES, max_length=1, null=True, blank=True)
    description = models.TextField(_('description'), null=True, blank=True)
    active_from = models.DateField(_('active_from'), null=True, blank=True)
    active_to = models.DateField(_('active_to'), null=True, blank=True)

    picture = models.ImageField(upload_to='images', width_field='picture_width', height_field='picture_height', null=True, blank=True)
    picture_width = models.PositiveIntegerField(null=True)
    picture_height = models.PositiveIntegerField(null=True)

    def __unicode__(self):
		#return u"{0} {1}".format(self.first_name, self.last_name)
        return unicode(self.first_name+" "+self.last_name)

    def is_active(self):
		return self.active_from <= datetime.date.today() <= self.active_to

    def picture_url(self):
        if self.picture:
            return self.picture.url
        return settings.STATIC_URL + 'img/default.png'

    def picture_absolute_url(self):
		return settings.BASE_URL + self.picture_url()


class ServiceProviderEmployeeImage(models.Model):
	image = models.ImageField(upload_to='images', width_field='image_width', height_field='image_height', null=False, blank=False)
	image_width = models.PositiveIntegerField(null=True)
	image_height = models.PositiveIntegerField(null=True)
	delete_image = models.BooleanField()
	service_provider_employee = models.ForeignKey(ServiceProviderEmployee, null=False)

enarocanje/service/models.py
import datetime

from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.utils.translation import ugettext_lazy as _, ugettext

from enarocanje.accountext.models import ServiceProvider, User

class Category(models.Model):
	name = models.CharField(_('name'), max_length=100)

	def __unicode__(self):
		return "%s" % (self.name)

class Service(models.Model):
	MALE = 'm'
	FEMALE = 'f'
	SEX_SERVICE_CHOICES = (
		(MALE, _('Male')),
		(FEMALE, _('Female')),
	)

	service_provider = models.ForeignKey(ServiceProvider, related_name='services')
	name = models.CharField(_('name'), max_length=100)
	duration = models.PositiveIntegerField(_('duration'))
	description = models.TextField(_('description'), null=True, blank=True)
	price = models.DecimalField(_('price'), max_digits=7, decimal_places=2, null=True, blank=True)
	sex = models.CharField(_('sex'), choices=SEX_SERVICE_CHOICES, max_length=1, null=True, blank=True)
	category = models.ForeignKey(Category, null=True, blank=True)
	active_until = models.DateField(_('active until'), null=True, blank=True)

	def __unicode__(self):
		return unicode(self.name)

	def duration_with_unit(self):
		return u'%dmin' % self.duration

	def get_discount(self):
		try:
			return self.discounts.get(valid_from__lte=datetime.date.today(), valid_to__gte=datetime.date.today())
		except ObjectDoesNotExist:
			return None

	def discounted_price(self):
		discount = self.get_discount()
		if discount:
			return self.price - discount.discount * self.price / 100
		else:
			return self.price

	def price_with_unit(self):
		discount = self.get_discount()
		if discount:
			return u'%s\u20ac (%s -%d%%)' % (self.discounted_price(), ugettext(_('with')), discount.discount)
		else:
			return u'%s\u20ac' % self.price

	def is_active(self):
		return self.active_until is None or self.active_until >= datetime.date.today()

class Discount(models.Model):
	service = models.ForeignKey(Service, related_name='discounts', verbose_name=_('service'))
	discount = models.PositiveIntegerField(_('discount'))
	valid_from = models.DateField(_('discount valid from'))
	valid_to = models.DateField(_('discount valid to'))

	def discount_with_unit(self):
		return u'%d%%' % self.discount

class Comment(models.Model):
	service = models.ForeignKey(Service, related_name='comments', verbose_name=_('service'))
	author = models.ForeignKey(User, related_name='comments', verbose_name=_('author'))
	body = models.TextField(_('body'))
	created = models.DateTimeField(auto_now_add=True)

enarocanje/ServiceProviderEmployee/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.forms.models import inlineformset_factory, BaseInlineFormSet
from django.utils.translation import ugettext_lazy as _

from enarocanje.common.timeutils import is_overlapping
from enarocanje.common.widgets import ClearableImageInput
from enarocanje.common.widgets import BootstrapDateInput
from enarocanje.service.models import Service
from models import ServiceProviderEmployee, ServiceProviderEmployeeImage


# 2.4.2014 RokA; Form for adding and editing Service Provider Employees
class ServiceProviderEmployeeForm(ModelForm):

    #picture = forms.ImageField(widget=ClearableImageInput(), required=False)
    active_from = forms.DateField(widget=BootstrapDateInput(), required=False, label=_('Active from'))
    active_to = forms.DateField(widget=BootstrapDateInput(), required=False, label=_('Active to'))


    class Meta:
        model = ServiceProviderEmployee
        # all fields except service_provider and service (you can only create your own services)
        exclude = ('picture_width', 'picture_height', 'service')
        fields = ('picture', 'active_from','active_to','first_name','last_name','description')

    def __init__(self, *args, **kwargs):
        super(ServiceProviderEmployeeForm, self).__init__(*args, **kwargs)
        #self.fields('service').label = _('Service')
        self.fields['first_name'].label = _('First name')
        self.fields['last_name'].label = _('Last name')
        #self.fields['sex'].label = _('Sex')
        self.fields['description'].label = _('Employee description')
        #self.fields['active_from'].label = _('Employee active from')
        #self.fields['active_to'].label = _('Employee active to')

class ServiceProviderEmployeeImageForm(ModelForm):
	image = forms.ImageField(required=True, label=_('Upload an image'))

	class Meta:
		model = ServiceProviderEmployeeImage
		exclude = ('image_width', 'image_height', 'service_provide_employee', 'delete_image')

enarocanje/ServiceProviderEmployee/views.py
# Create your views here.
import datetime
import json
import urllib

from django.conf import settings
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.exceptions import FieldError
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.template.loader import render_to_string
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from enarocanje.accountext.decorators import for_service_providers
from enarocanje.accountext.forms import ServiceProviderImageForm
from enarocanje.accountext.models import ServiceProvider, ServiceProviderImage, Category as SPCategory
from enarocanje.reservations.models import Reservation
from forms import ServiceProviderEmployeeForm
from models import ServiceProviderEmployee

# Choices for sorting customers
SORT_CHOICES_EMPLOYEES = (
    (_('Order by last name'), 'last_name'),
    #TODO: dodatno
)

# Method for constructing url addresses
def construct_url_employees( q, sor, page):
    parts = []
    if q:
        parts.append('q=%s' % q)
    if sor != 'last_name':
        parts.append('sort=%s' % sor)
    if page:
        parts.append('page=%s' % page)
    if parts:
        return '?' + '&'.join(parts)
    return reverse(myemployees)


@for_service_providers
def myemployees(request):
    employees = request.user.service_provider.employees.all()
    # locals() returns a dictionary of variables in the local scope (request and services in this case)
    return render_to_response('serviceprovideremployee/myemployees.html', locals(), context_instance=RequestContext(request))

# Add a new employees
@for_service_providers
def add(request):
    if request.method == 'POST':
        # if method was post (form submission), fill form from post data
        form = ServiceProviderEmployeeForm(request.POST, request.FILES)
        form_valid = form.is_valid()
        if form_valid:
            # if form is valid, save it and redirect back to myemployees
            # commit=False tells form to not save the object to the database just yet and return it instead
            employee = form.save(commit=False)
            # set service_provider to the current user before we save the object to the database
            employee.service_provider = request.user.service_provider
            employee.save()
            return HttpResponseRedirect(reverse(myemployees))
    else:
        # on get request create empty form
        form = ServiceProviderEmployeeForm()
    # render form - new (get request) or invalid with error messages (post request)
    return render_to_response('serviceprovideremployee/add.html', locals(), context_instance=RequestContext(request))

# Edit existing employee
@for_service_providers
def edit(request, id):
    employee = get_object_or_404(ServiceProviderEmployee, service_provider=request.user.service_provider, id=id)
    if request.method == 'POST':
        form = ServiceProviderEmployeeForm(request.POST, request.FILES, instance=employee)
        form_valid = form.is_valid()
        if form_valid:
            form.save()
            return HttpResponseRedirect(reverse(myemployees))
    else:
        form = ServiceProviderEmployeeForm(instance=employee)
    return render_to_response('serviceprovideremployee/edit.html', locals(), context_instance=RequestContext(request))

# Activate/deactivate Employee
@for_service_providers
def manage(request):
    if request.method == 'POST':
        employee = get_object_or_404(ServiceProviderEmployee, service_provider=request.user.service_provider, id=request.POST.get('employee'))
        if request.POST.get('action') == 'activate':
            employee.active_to = None
            employee.save()
        if request.POST.get('action') == 'deactivate':
            employee.active_to = datetime.date.today() - datetime.timedelta(1)
            employee.save()
        if request.POST.get('action') == 'delete':
            employee.delete()
    return HttpResponseRedirect(reverse(myemployees))

templates/serviceprovideremployee/add.html
{% extends 'serviceprovideremployee/edit.html' %}

{% load i18n %}

{% block content_title %}{% trans "Add Employee" %}{% endblock %}

templates/serviceprovideremployee/edit.html
{% extends 'main.html' %}

{% load url from future %}
{% load i18n %}
{% load bootstrap_toolkit %}

{% block main_nav_myemployees %}active{% endblock %}

{% block content %}

<h1>{% block content_title %}{% trans 'Edit Employee' %}{% endblock %}</h1>


<form enctype="multipart/form-data" method="POST" action="" class="">
		{% csrf_token %}
		<div class="row">
			<div class="span5">
				{% if form.non_field_errors %}
					{% include "bootstrap_toolkit/non_field_errors.html" %}
				{% endif %}
				{% for field in form.hidden_fields %}
					{{ field }}
				{% endfor %}
				{{ form.first_name|as_bootstrap }}
				{{ form.last_name|as_bootstrap }}
				{{ form.description|as_bootstrap }}
                {{ form.active_from|as_bootstrap }}
                {{ form.active_to|as_bootstrap }}
                {{ form.picture|as_bootstrap }}
			</div>
		</div>
		<div class="form-actions">
			<button class="btn btn-primary" type="submit" name="action">{% trans "Save" %}</button>
			<a class="btn" href="{% url 'myemployees' %}">{% trans "Cancel" %}</a>
		</div>
</form>

{% endblock %}

{% block javascript %}
	{{ block.super }}
	(function(){
		function dateFields(el) {
			el.find('.date-field').parent().datetimepicker({pickTime: false, language: '{{ request.LANGUAGE_CODE }}'});
			$(document).trigger('sizing');
		}
		dateFields($('body'));
	})();
{% endblock %}

templates/serviceprovideremployee/myemployees.html
{% extends 'main.html' %}

{% load url from future %}
{% load i18n %}
{% load bootstrap_toolkit %}
{% load provider %}

{% block main_nav_myemployees %}active{% endblock %}



{% block content %}
<h1>{% trans 'My Employees' %}</h1>

<ul class="nav nav-pills pull-right visible-desktop">
	{% for sort in sort_choices %}
		<li {% if sort.2 %}class="active"{% endif %}><a href="{{ sort.1 }}">{{ sort.0 }}</a></li>
	{% endfor %}
    </ul>
<ul class="nav nav-tabs">

	<li class="active">
		<a href="{% url 'myemployees' %}">{% trans 'Employees' %}</a>
	</li>
</ul>

	<div class="row twoone-main">
		<div class="span2">
			<ul class="nav nav-list">
				<form action="">
					<input type="text" name="q" placeholder="{% trans "Search" %}" value="{% if q %}{{ q }}{% endif %}" style="width: 100%" />
					{% if sor != 'date' %}<input type="hidden" name="sort" value="{{ sor }}"/>{% endif %}
				</form>

				<li class="nav-header hidden-desktop">{% trans "Order by" %}</li>
				{% for sort in sort_choices %}
					<li class="hidden-desktop {% if sort.2 %}active{% endif %}"><a href="{{ sort.1 }}">{{ sort.0 }}</a></li>
				{% endfor %}
			</ul>
			<br/>
		</div>
		<div class="span10"> <!-- TO SPREMENI kot v myservices!!! -->
			{% if employees %}
				<!-- TBA -->
                <div id="no-more-tables">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    {% trans 'First Name' %}
                                </th>
                                <th>
                                    {% trans 'Last name' %}
                                </th>
                                <th>
                                    {% trans 'Description' %}
                                </th>
                                <th>
                                    {% trans 'Active From' %}
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for employee in employees %}
                                <tr>
                                    <td data-title="{% trans 'First Name' %}">
                                        {{ employee.first_name }}
                                    </td>
                                    <td data-title="{% trans 'Last Name' %}">
                                        {{ employee.last_name }}
                                    </td>
                                    <td data-title="{% trans 'Description' %}">
                                        {{ employee.description }}
                                    </td>
                                    <td data-title="{% trans 'Active From' %}">
                                        {{ employee.active_from }}
                                    </td>
                                    <td data-title="{% trans 'Actions' %}">
                                        <a class="btn" href="{% url 'editemployee' employee.id %}">{% trans "Edit" %}</a>
                                        <a href="{% url 'employeeworkinghours' employee.id %}" class="btn">{% trans "Edit working hours" %}</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

				{% with employees as paginator %}
					{% include "browse/pagination.html" %}
				{% endwith %}
			{% else %}
				{% trans "No employees found." %}
			{% endif %}
		</div>

	</div>
    <div class="form-actions">
                    <a class="btn btn-primary" href="{% url 'addemployee' %}">{% trans "Add employee" %}</a>
         </div>
{% endblock %}

{% block javascript %}
	{{ block.super }}
    (function() {
        $('#id_category, #id_provider, #id_discount, #id_orderby, #id_ascdesc').change(function() {
                $('#search-form').submit();
            });
    });
{% endblock %}