enarocanje/reservations/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('enarocanje.reservations',
	url(r'^myreservations$', 'views.myreservations', name='myreservations_calendar'),
    url(r'^allreservations/$', 'views.allreservations', name='myreservations_table'),
    url(r'^allreservations/this$', 'views.allreservations_this', name='myreservations_thisweek'),
    url(r'^allreservations/next$', 'views.allreservations_next', name='myreservations_nextweek'),
	url(r'^myreservations/gcal/$', 'gcal.edit', name='gcal'),
	url(r'^myreservations/gcal/callback$', 'gcal.callback', name='gcalcallback'),

	url(r'^services/(?P<id>\d+)$', 'views.reservation2', name='service2'),
    # 3.5.2014 RokA; try to pass employee_id to view.reservation
    url(r'^services/(?P<id>\d+)/(?P<employee_id>\d+)$', 'views.reservation', name='service'),
	# RokA; and same for next step url
	url(r'^services/(?P<id>\d+)/reservation$', 'views.reservation2', name='reservation2'),
    url(r'^services/(?P<id>\d+)/(?P<employee_id>\d+)/reservation$', 'views.reservation', name='reservation'),
	url(r'^calendar.json$', 'rcalendar.calendarjson', name='calendarjson'),
	url(r'^dogodki.json$', 'reservationsCalendar.koledar_json', name='dogodki'),
)

enarocanje/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^accounts/signup/$', 'enarocanje.accountext.views.singup'),
    url(r'^accounts/signup/provider/$', 'enarocanje.accountext.views.providersignup'),
	url(r'^accounts/profile/$', 'enarocanje.accountext.views.account_profile', name='account_profile'),

	url(r'^', include('enarocanje.service.urls')),
	url(r'^', include('enarocanje.workinghours.urls')),
	url(r'^', include('enarocanje.reservations.urls')),
	url(r'^', include('enarocanje.coupon.urls')),
    url(r'^', include('enarocanje.customers.urls')),
    url(r'^', include('enarocanje.ServiceProviderEmployee.urls')),
    url(r'^', include('enarocanje.mailservice.urls')),

	url(r'^web/(?P<serviceProviderWeb>\w+)/$', 'enarocanje.accountext.views.ServiceProviderWeb', name='provider_web'),

	# External apps
	url(r'^accounts/', include('allauth.urls')),

	# Django admin
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	url(r'^admin/', include(admin.site.urls)),

    # Cookies
    url(r'^cookies/$', TemplateView.as_view(template_name="cookies.html"),name='cookies'),
)

if settings.DEBUG:
	urlpatterns += patterns('',
		(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
	)

enarocanje/reservations/models.py
from oauth2client.django_orm import CredentialsField
from south.modelsinspector import add_introspection_rules

from django.db import models
from django.utils.translation import ugettext_lazy as _

from enarocanje.accountext.models import User, ServiceProvider
from enarocanje.customers.models import Customer
from enarocanje.service.models import Service
from enarocanje.ServiceProviderEmployee.models import ServiceProviderEmployee

add_introspection_rules([], ['^oauth2client\.django_orm\.CredentialsField'])

class Reservation(models.Model):

    """Reservation model - who made a reservation and when"""
    user = models.ForeignKey(User, null=True)  # null for gcal imported reservations
    customer = models.ForeignKey(Customer, null=True)
    service = models.ForeignKey(Service, null=True, on_delete=models.SET_NULL)  # service can be deleted
    #8.4.2014 RokA; add service provider employee to choose for reservation
    service_provider_employee = models.ForeignKey(ServiceProviderEmployee, null=True)
    date = models.DateField(null=False, blank=False)
    time = models.TimeField(null=False, blank=False)
    gcalid = models.CharField(max_length=255, null=True)
    isfromgcal = models.BooleanField(default=False)
    # Is confirmed from service provider
    is_confirmed = models.BooleanField(default=False)
    is_deny = models.BooleanField(default=False)
    # Backup fields for user
    user_fullname = models.CharField(_('name'), max_length=60, null=True)
    user_phone = models.CharField(_('phone number'), max_length=100, null=True)
    user_email = models.CharField(_('email address'), max_length=100, null=True)
    service_notifications = models.BooleanField(default=False)
    # Backup fields if the service is changed or deleted
    service_provider = models.ForeignKey(ServiceProvider, related_name='reservations')
    service_name = models.CharField(_('name'), max_length=100)
    service_duration = models.PositiveIntegerField(_('duration'))
    service_price = models.DecimalField(_('price'), max_digits=7, decimal_places=2, null=True, blank=True)

    # Comments email
    emailsent = models.BooleanField(default=False)

    # Timestamps
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, db_index=True)
    gcalimported = models.DateTimeField(null=True)

    # Klemen 27.4.2014: Fields for determining if customer attended the service and their rating
    attended = models.BooleanField(default=True)
    rating = models.IntegerField(_('rating'), null=True, blank=True)


    def __unicode__(self):
        return str(self.date) + " User: " + str(self.user) + " Service: " + str(self.service)

    def short_desc(self):
        """Default short description visible on reservation button"""
        return str(self.id)

    class Meta:
        unique_together = ('service_provider', 'service_provider_employee', 'gcalid')

class GCal(models.Model):
    id = models.ForeignKey(ServiceProvider, primary_key=True)
    credential = CredentialsField()

enarocanje/reservations/views.py
import base64
import datetime
import pdb
import pickle
import string
import urllib

from django.conf import settings
from django.core.mail import send_mail
from django.core.mail import send_mass_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.urlresolvers import reverse
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.template.loader import render_to_string
from django.utils.translation import ugettext_lazy as _
from setuptools.command.sdist import re_finder

from enarocanje.accountext.decorators import for_service_providers
from enarocanje.accountext.models import User
from enarocanje.common.timeutils import datetime_to_url_format
from enarocanje.coupon.models import Coupon
from enarocanje.customers.models import Customer
from enarocanje.customers.views import construct_url_customers
from enarocanje.reservations.gcal import sync
from enarocanje.reservations.models import Reservation
from enarocanje.service.models import Service
from enarocanje.ServiceProviderEmployee.models import ServiceProviderEmployee
from enarocanje.tasks.mytasks import *
from enarocanje.workinghours.models import WorkingHours, EmployeeWorkingHours
from forms import ReservationForm, NonRegisteredUserForm, ReservationsForm
from rcalendar import getMinMaxTime, getEmployeeMinMaxTime


# Choices for sorting reservations
SORT_CHOICES_RESERVATIONS = (
    (_('Order by service'), 'service'),
    (_('Order by date'), 'date'),
    (_('Order by customer'), 'customer'),
    (_('Order by employee'), 'employee'),
)

SEARCH_CHOICES_RESERVATIONS = (
    (_('Service'), 'service'),
    (_('Customer'), 'customer'),
    (_('Employee'), 'employee'),
)

# Method for constructing url addresses
def construct_url_reservations( q, src, sor, page):
    parts = []
    if q:
        parts.append('q=%s' % q)
    if src != 'service':
        parts.append('src=%s' % src)
    if sor != 'name':
        parts.append('sort=%s' % sor)
    if page:
        parts.append('page=%s' % page)
    if parts:
        return '?' + '&'.join(parts)
    return reverse(allreservations)


# Service reservations
def reservation2(request, id):
    return reservation(request, id, 0)

def reservation(request, id, employee_id):
    service = get_object_or_404(Service, id=id)
    #Klemen: dobi zaposlenega za to storitev, ce je bil dolocen


    if employee_id > 0:
        service_provider_employee_obj = get_object_or_404(ServiceProviderEmployee, id=employee_id)
    else:
        service_provider_employee_obj = None

    if not service.is_active():
        raise Http404



    minTime, maxTime = getMinMaxTime(service.service_provider)



    if request.method != 'POST':
        # ce je zaposleni dolocen, ga daj kot initial
        if service_provider_employee_obj:
            form = ReservationForm(request, workingHours=None, service=service, serviceProviderEmployee=service_provider_employee_obj, initial={"service_provider_employee":service_provider_employee_obj})
        else:
            #ce se ni bil izbran
            form = ReservationForm(request, workingHours=None, service=service, serviceProviderEmployee=service_provider_employee_obj)
        service_provider = service.service_provider
        data = {'service_provider_id': service.service_provider_id} # 'service_provider_employee_id': service_provider_employee_obj.id }
        return render_to_response('reservations/reservation.html', locals(), context_instance=RequestContext(request))

    # POST
    step = request.POST.get('step', '1')

    try:
        data = pickle.loads(base64.b64decode(request.POST.get('data')))  # Serializes an object from request
    except:
        raise Http404

    if service_provider_employee_obj:
        workingHours = WorkingHours.objects.filter(service_provider_id=service.service_provider_id)
    else:
        workingHours = EmployeeWorkingHours.objects.filter(service=service, service_provider_employee=service_provider_employee_obj)




    formNonRegisteredUser = NonRegisteredUserForm()

    if step == '1':
        # Service, date, time
        # form = ReservationForm(request.POST, workingHours='gergerre')
        #service_provider_employee_choice = request.POST.get['service_provider_employee']
        #print service_provider_employee_choice
        form = ReservationForm(request, request.POST, workingHours=workingHours, service=service, serviceProviderEmployee=service_provider_employee_obj)

        if form.is_valid():
            data['date'] = form.cleaned_data['date']
            data['time'] = form.cleaned_data['time']
            data['number'] = form.cleaned_data['number']
            service_provider_employee_obj = form.cleaned_data['service_provider_employee']
            # ce je bil izbran zaposleni, shrani njegov id in ga prenesi v naslednje step-e

            if service_provider_employee_obj:
                data['service_provider_employee'] = form.cleaned_data['service_provider_employee'].id

            if request.user.is_authenticated():
                data['user_id'] = request.user.id
                data['name'] = request.user.get_full_name()
                data['phone'] = request.user.phone
                data['email'] = request.user.email
                data['service_notifications'] = request.user.service_notifications
                return render_to_response('reservations/confirmation.html', locals(), context_instance=RequestContext(request))

            return render_to_response('reservations/userinfo.html', locals(), context_instance=RequestContext(request))
        if service_provider_employee_obj:
            form = ReservationForm(request, workingHours=None, service=service, serviceProviderEmployee=service_provider_employee_obj, initial={"service_provider_employee":service_provider_employee_obj})
        else:
            #ce se ni bil izbran
            form = ReservationForm(request, workingHours=None, service=service, serviceProviderEmployee=service_provider_employee_obj)
        service_provider = service.service_provider
        data = {'service_provider_id': service.service_provider_id} # 'service_provider_employee_id': service_provider_employee_obj.id }

        return render_to_response('reservations/reservation.html', locals(), context_instance=RequestContext(request))

    if step == '2':
        # User info
        if data.get('date') is None or data.get('time') is None:
            raise Http404
        formNonRegisteredUser = NonRegisteredUserForm(request.POST)
        if formNonRegisteredUser.is_valid():
            data['name'] = formNonRegisteredUser.cleaned_data['name']
            data['phone'] = formNonRegisteredUser.cleaned_data['phone']
            data['email'] = formNonRegisteredUser.cleaned_data['email']
            data['service_notifications'] = formNonRegisteredUser.cleaned_data['service_notifications']
            return render_to_response('reservations/confirmation.html', locals(), context_instance=RequestContext(request))

        return render_to_response('reservations/userinfo.html', locals(), context_instance=RequestContext(request))

    if step == '3':
        # Confirmation

        #inicializiraj objekt zaposlenega glede na to, kateri je bil prej izbran
        if data.get('service_provider_employee'):
            service_provider_employee_obj = get_object_or_404(ServiceProviderEmployee, id=data.get('service_provider_employee'))
        else:
            service_provider_employee_obj = None
        if data.get('date') is None or data.get('time') is None:  # or data.get('user_id') is None:
            raise Http404
        if data.get('user_id') is not None:
            ruser = get_object_or_404(User, id=data.get('user_id'))
        else:
            ruser = None

        sync(service.service_provider)

        # Checking again if form for reservation is valid
        form = ReservationForm(request, {'date': data.get('date'), 'time': data.get('time')}, workingHours=workingHours, service=service, serviceProviderEmployee=service_provider_employee_obj)
        #form.fields['service_provider_employee']=service_provider_employee_obj

        if form.is_valid():
            # Add a customer
            user_mail = None
            if ruser is None:
            # If an unregistered customer performs reservation
                customer_name = data.get('name').split()
                customer = Customer(name=customer_name[0], last_name=customer_name[len(customer_name)-1], phone=data.get('phone'), email=data.get('email'), full_name=data.get('name'))
                user_mail = data.get('email')
            else:
                # If a registered customer performs reservation
                customer = Customer(name=ruser.first_name, last_name=ruser.last_name, phone=ruser.phone, email=ruser.email, full_name=ruser.first_name+' '+ruser.last_name)
                user_mail = ruser.email
            try:
                Customer.objects.get(email=data.get('email'))

            except:
                # Save a customer if they are not already in
                customer.save()
            # Save a reservation
            customer = Customer.objects.get(email=user_mail)
            customer.last_reservation=datetime.datetime.today()
            customer.save(update_fields=['last_reservation'])
            reserve = Reservation(user=ruser, service=service, date=data['date'], time=data['time'], customer=customer, service_notifications=data['service_notifications'])
            # Add backup fields
            reserve.user_fullname = data.get('name')
            reserve.user_phone = data.get('phone')
            reserve.user_email = data.get('email')
            reserve.service_provider = service.service_provider
            reserve.service_name = service.name
            reserve.service_duration = service.duration

templates/reservations/allreservations.html
{% extends 'main.html' %}

{% load url from future %}
{% load i18n %}
{% load bootstrap_toolkit %}

{% block main_nav_reservations %}active{% endblock %}

{% block content %}
<h1>{% trans 'My Reservations' %}</h1>
    <ul class="nav nav-pills pull-right visible-desktop" id="id_sort">
	{% for sort in sort_choices %}
		<li {% if sort.2 %}class="active"{% endif %}><a href="{{ sort.1 }}">{{ sort.0 }}</a></li>
	{% endfor %}
    </ul>
	<ul class="nav nav-tabs">
		<li>
			<a href="{% url 'myreservations_calendar' %}">{% trans 'Calendar' %}</a>
		</li>
        <li class="dropdown active">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            All Reservations
            <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
               <li> <a href="{% url 'myreservations_table' %}">{% trans 'All time' %}</a> </li>
               <li><a href="{% url 'myreservations_thisweek' %}">{%  trans 'This week' %}</a></li>
               <li><a href="{% url 'myreservations_nextweek' %}">{%  trans 'Next week' %}</a></li>
            </ul>
        </li>
		{% if res_confirm == True %}
			<li>
			<a href="{% url 'myunconfirmedreservations' %}">{% trans 'Unconfirmed reservations' %}</a>
		</li>
		{% endif %}
    </ul>
         <form method="POST" action="" id="filter-form" class="form-horizontal">
                {% csrf_token %}
                {{ resForm | as_bootstrap }}
                </form>
    <br />
	<div class="row-fluid">
		<div class="span2">
			<ul class="nav nav-list">
				<form action="" >
					<input type="text" name="q" placeholder="{% trans "Search" %}" value="{% if q %}{{ q }}{% endif %}" style="width: 100%" />
					{% if sor != 'date' %}<input type="hidden" name="sort" value="{{ sor }}"/>{% endif %}
                    {% if src != 'service' %}<input type="hidden" name="src" value="{{ src }}"/>{% endif %}

				</form>
                <li class="nav-header">{% trans "Search by" %}</li>
				{% for search in search_choices %}
					<li class=" {% if search.2 %}active{% endif %}"><a href="{{ search.1 }}">{{ search.0 }}</a></li>
				{% endfor %}
                <hr />
				<li class="nav-header hidden-desktop">{% trans "Order by" %}</li>
				{% for sort in sort_choices %}
					<li class="hidden-desktop {% if sort.2 %}active{% endif %}"><a href="{{ sort.1 }}">{{ sort.0 }}</a></li>
				{% endfor %}

			</ul>
			<br/>
		</div>
		<div class="span10">
			{% if reservations %}

                <div >
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    {% trans 'Customer' %}
                                </th>
                                <th>
                                    {% trans 'Service' %}
                                </th>
                                <th>
                                    {% trans 'Date' %}
                                </th>
                                <th>
                                    {% trans 'Time' %}
                                </th>
                                <th>
                                    {% trans 'Employee' %}
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for reservation in reservations %}
                                <tr>
                                    <td data-title="{% trans 'Customer' %}">
                                        {{ reservation.customer.full_name}}
                                    </td>
                                    <td data-title="{% trans 'Service' %}">
                                        {{ reservation.service_name }}
                                    </td>
                                    <td data-title="{% trans 'Date' %}">
                                        {{ reservation.date }}
                                    </td>
                                    <td data-title="{% trans 'Time' %}">
                                        {{ reservation.time }}
                                    </td>
                                    <td data-title="{% trans 'Employee' %}">
                                       {% if reservation.service_provider_employee %} {{ reservation.service_provider_employee }} {% else %} {% trans "No employee selected" %} {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>



				{% with reservations as paginator %}
					{% include "browse/pagination.html" %}
				{% endwith %}
			{% else %}
				{% trans "No reservations found." %}
			{% endif %}
		</div>

	</div>

{% endblock %}

{% block javascript %}
	{{ block.super }}
    	$('#filter-form').change(function() {
		$('#filter-form').submit();
	});

{% endblock %}

templates/reservations/alreadyreserved.html
{% extends "main.html" %}

{% load url from future %}
{% load i18n %}

{% block content %}

<h1>{% trans 'Sorry, someone else has made a reservation in the meantime. Pick a different date or time. Thank you.' %}</h1>
{% if service_provider_employee_obj %}
    <a href="{% url 'service' service.id service_provider_employee_obj.id %}" class="btn">{% trans "Try again" %}</a>
{% else %}
    <a href="{% url 'service2' service.id %}" class="btn">{% trans "Try again" %}</a>
{% endif %}

{% endblock %}

templates/reservations/base.html
{% extends "main.html" %}

{% load url from future %}
{% load i18n %}
{% load reservation %}

{% block content %}

<h1>{% trans 'Reservation' %}</h1>

<form method="POST" action="">
	{% csrf_token %}

	<input type="hidden" name="data" value="{{ data|encode_data }}" />

	{% block reservation_content %}
	{% endblock %}
</form>

{% endblock %}

templates/reservations/reservation.html
{% extends 'service/service.html' %}

{% load url from future %}
{% load i18n %}
{% load bootstrap_toolkit %}
{% load reservation %}

{% block service_nav_reservation %}active{% endblock %}

{% block service_content %}

{% if minTime and maxTime %}
{% if service_provider_employee_obj %}
	<form method="POST" action="{% url 'reservation' service.id service_provider_employee_obj.id%}">
{% else %}
    <form method="POST" action="{% url 'reservation2' service.id%}">
{% endif %}
		{% csrf_token %}

		<input type="hidden" name="data" value="{{ data|encode_data }}" />

		<div class="row">
			<div class="span6">
				{{ form.date|as_bootstrap }}
			</div>
            <div class="span6">
				{{ form.service_provider_employee|as_bootstrap }}

			</div>
			<div class="span6">
				{{ form.time|as_bootstrap }}
			</div>
		</div>

		<div id='calendar'></div>

		<br/>
		<b>{% trans "If you have a COUPON, then enter the coupon's number" %}:</b><br/>
		{{ form.number|as_bootstrap }}

		<div class="form-actions">

			<input type="submit" class="btn btn-primary" value="{% trans "Make a reservation" %}">
		</div>
	</form>
{% endif %}

{% endblock %}

{% block javascript %}
	{{ block.super }}
	{% if minTime and maxTime %}

    $('#id_service_provider_employee').change(function(){

        refreshCalendar()
    })

    function refreshCalendar ()
    {
        $('#calendar').fullCalendar( 'removeEventSource', { url:'{% url 'calendarjson' %}'})

            $('#calendar').fullCalendar( 'addEventSource', {
                url: '{% url 'calendarjson' %}',
                type: 'GET',
                data: readParameters()
            })
    }

    function readParameters ()

    {

         return {

             employee_id: $('#id_service_provider_employee').val(),
             service_provider_id:'{{ service_provider.id }}',
             service_id: '{{ service.id }}',
             start: '{{ minTime }}',
             end: '{{ maxTime }}'

         }
    }
	(function() {
		var date = new Date(), selectedEvent = null;
		function updateDate(ndate) {
			$('#calendar').fullCalendar('removeEventSource', selectedEvent);
			date = ndate;
			var dateEnd = new Date(date);
			dateEnd.setMinutes(dateEnd.getMinutes() + {{ service.duration }});
			selectedEvent = [{
				title: '{% trans 'Your reservation' %}',
				start: date,
				end: dateEnd
			}];
			$('#calendar').fullCalendar('addEventSource', selectedEvent);
		}

		function changeDate(ev) {
			date.setFullYear(ev.localDate.getFullYear());
			date.setMonth(ev.localDate.getMonth());
			date.setDate(ev.localDate.getDate());
			updateDate(date);
			$('#calendar').fullCalendar('gotoDate', date);
		}

		function changeTime(ev) {
			date.setHours(ev.localDate.getHours());
			date.setMinutes(ev.localDate.getMinutes());
			updateDate(date);
			$('#calendar').fullCalendar('gotoDate', date);
		}

		function viewDisplay(view) {
			if (view.start <= new Date()) {
				$("#calendar .fc-button-prev").addClass('fc-state-disabled');
			} else {
				$("#calendar .fc-button-prev").removeClass('fc-state-disabled');
			}
			if (view.name == 'agendaWeek') {
				if (date < view.start) {
					date.setDate(date.getDate() + 7);
				}
				if (date >= view.end) {
					date.setDate(date.getDate() - 7);
				}
			} else {
				if (date < view.start) {
					date.setDate(date.getDate() + 1);
				}
				if (date >= view.end) {
					date.setDate(date.getDate() - 1);
				}
			}
			updateDate(date);
			datePicker.data('datetimepicker').setLocalDate(date);
			timePicker.data('datetimepicker').setLocalDate(date);
		}

		function dayClick(ndate, allDay, jsEvent, view) {
			updateDate(ndate);
			$('#calendar').fullCalendar('gotoDate', date);
			datePicker.data('datetimepicker').setLocalDate(date);
			timePicker.data('datetimepicker').setLocalDate(date);
		}

		var now = new Date();
		now.setMinutes(now.getMinutes() - now.getTimezoneOffset());

		var timePicker = $('.time-field').parent().datetimepicker({pickDate: false, pickSeconds: false, minuteStep: 15, language: '{{ request.LANGUAGE_CODE }}'}).on('changeDate', changeTime);
		var datePicker = $('.date-field').parent().datetimepicker({pickTime: false, startDate: now, language: '{{ request.LANGUAGE_CODE }}'}).on('changeDate', changeDate);

		var dateDate = datePicker.data('datetimepicker').getLocalDate();
		var dateTime = timePicker.data('datetimepicker').getLocalDate();
		date.setFullYear(dateDate.getFullYear());
		date.setMonth(dateDate.getMonth());
		date.setDate(dateDate.getDate());
		date.setHours(dateTime.getHours());
		date.setMinutes(dateTime.getMinutes());
		date.setSeconds(0);

		$('#calendar').fullCalendar({
			header: {
				left: 'prev,next today',
				center: '',
				right: 'agendaWeek,agendaDay'
			},

			/* sets the current view */
			defaultView: (document.width >= 800) ? 'agendaWeek' : 'agendaDay',

			/* sets the specific date */
			year: date.getFullYear(),
			month: date.getMonth(),
			date: date.getDate(),

			minTime: '{{ minTime|date:"H:i" }}',
			maxTime: '{{ maxTime|time:"H:i" }}',

			editable: false,
			allDayDefault: false,
			allDaySlot: false,
			height: 100000,
			slotMinutes: 15,

			/* callbacks */
			viewDisplay: viewDisplay,
			dayClick: dayClick,

			/* translation */
			buttonText: {
				today: '{% trans 'today' %}',
				month: '{% trans 'month' %}',
				week: '{% trans 'week' %}',
				day: '{% trans 'day' %}'
			},
			monthNames: ['{% trans 'January' %}', '{% trans 'February' %}', '{% trans 'March' %}', '{% trans 'April' %}', '{% trans 'May' %}', '{% trans 'June' %}', '{% trans 'July' %}', '{% trans 'August' %}', '{% trans 'September' %}', '{% trans 'October' %}', '{% trans 'November' %}', '{% trans 'December' %}'],
			monthNamesSort: ['{% trans 'Jan' %}', '{% trans 'Feb' %}', '{% trans 'Mar' %}', '{% trans 'Apr' %}', '{% trans 'May' %}', '{% trans 'Jun' %}', '{% trans 'Jul' %}', '{% trans 'Aug' %}', '{% trans 'Sep' %}', '{% trans 'Oct' %}', '{% trans 'Nov' %}', '{% trans 'Dec' %}'],
			dayNames: ['{% trans 'Sunday' %}', '{% trans 'Monday' %}', '{% trans 'Tuesday' %}', '{% trans 'Wednesday' %}', '{% trans 'Thursday' %}', '{% trans 'Friday' %}', '{% trans 'Saturday' %}'],
			dayNamesShort: ['{% trans 'Sun' %}', '{% trans 'Mon' %}', '{% trans 'Tue' %}', '{% trans 'Wed' %}', '{% trans 'Thu' %}', '{% trans 'Fri' %}', '{% trans 'Sat' %}'],
			weekNumberTitle: '{% trans 'W' %}',
			allDayText: '{% trans 'all-day' %}',
			columnFormat: {
				month: 'ddd',
				week: 'ddd d.M.',
				day: 'dddd d.M.'
			},
			firstDay: 1,
			axisFormat: 'HH:mm',
			timeFormat: {
				agenda: 'H:mm{ - H:mm}'
			},

			/* events data */

			events: {
				url: '{% url 'calendarjson' %}',
				type: 'GET',
				data: readParameters ()
			}
		});

		$('#calendar-refresh').click(function() {
			$('#calendar').fullCalendar('refetchEvents');
		});
	})();
	{% endif %}
{% endblock %}